FROM ghcr.io/chenxiex/devcontainer-templates/devcontainer-python-uv-${templateOption:imageVariant}:latest

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
