FROM ghcr.io/chenxiex/devcontainer-templates/devcontainer-devops-${templateOption:imageVariant}:latest

# [Optional] Uncomment this section to install additional OS packages.
# RUN apk add --no-cache <your-package-list-here>
