name: Dev Container Build and Push Images

on:
  workflow_dispatch:
  schedule:
    - cron: "23 4 1 * *"
  push:
    branches: ["main"]
    paths:
      - "images/**"
      - ".github/workflows/devcontainer-build-and-push.yml"

jobs:
  build-and-push:
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: python-uv
            variant: 3-trixie
          - image: cpp-extra
            variant: debian13
          - image: cpp-extra
            variant: ubuntu24.04
    uses: chenxiex/reusable_workflow/.github/workflows/devcontainer-build-and-push.yml@main
    with:
      registry: ghcr.io
      image_name: "${{ github.repository }}/devcontainer-${{ matrix.image }}-${{ matrix.variant }}"
      sub_folder: "images/${{ matrix.image }}"
      build_variant: "${{ matrix.variant }}"
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
    permissions:
      contents: read
      packages: write
