name: images-cpp-extra

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "images/cpp-extra/**"
      - ".github/workflows/images-cpp-extra.yaml"

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: chenxiex/devcontainer/images/cpp-extra

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base-tag: [ "1-debian-12", "1-debian-11", "1-ubuntu-24.04", "1-ubuntu-22.04", "1-ubuntu-20.04" ]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        env:
          BASE_TAG: ${{ matrix.base-tag }}
        with:
          subFolder: images/cpp-extra
          imageName: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}
          imageTag: ${{ matrix.base-tag }}
          cacheFrom: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}
          push: always